language: perl
perl:
    - "5.36"
    - "5.32"
    - "5.30"
    - "5.20"
    - "5.10"
env:
  global:
    - PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
    - "cpanm Capture::Tiny"
    - "cpanm Term::ANSIColor@3.0"
    - "cpanm Test::Exception"
    - "cpanm Devel::StackTrace"
    - "cpanm Data::Dumper@2.160"
install:
    - "perl Makefile.PL && make test"
sudo: false
notifications:
    email: false

